# Setup
title: "모타겟의 엔진"
description: "게임, 영화 그리고 프로그래밍"
url: "https://mtg-pjh.github.io"
paginate: 1
baseurl: "https://mtg-pjh.github.io"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: "모타겟"
  url: "https://mtg-pjh.github.io"
  email: ""

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
